### ISSUE TITLE
Change profile pics to something more suitable to the Achievement (Adjust your changes also on Server)

### ISSUE THREAD

**Issue by na50r** [sopra-fs24-group-41/sopra-fs24-group-41-client#142]
So currently, I just put random profile pics into the Achievments so we can quickly confirm if our code works even after deployment. It would be better, if the profile pics you win through the Achievements are also somewhat related to the Achievement itself.
Like, "I am Speed", wouldn't it be cool to get McQueen?

**Comment by Aquamarine-12** [comment]
Should these profile pictures have a consistent style? If not, we could take some of them from games/cartoons
