### ISSUE TITLE
Ensure functionality where a lobby can be renamed.

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-client#20]

**Comment by Tmmn** [comment]
https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-client/commit/84179907db532741debc7d88aeeee31c59dc8254

**Comment by na50r** [comment]
Was implemented here: 84179907db532741debc7d88aeeee31c59dc8254
