### ISSUE TITLE
Display target word on screen

### ISSUE THREAD

**Issue by na50r** [sopra-fs24-group-41/sopra-fs24-group-41-client#50]

**Comment by Grizzlytron** [comment]
https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-client/commit/001bc5721f7658f1949b472f09f186c0e7a79337

**Comment by Grizzlytron** [comment]
Enhanced here by JacquelineUlken: https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-client/commit/f7ab333bd768cd2fc120b5be2f9d8e01ec56f91d
